### ISSUE TITLE
Support for Trailblazer 1.0 in new update to Rails 5

### ISSUE THREAD

**Issue by night91** [be9/acl9#108]
Support for Trailblazer 1.0 in new update to Rails 5.

**Comment by smathy** [comment]
I assume this is a request/question :)

Take a look at [the work I had done previously](https://github.com/be9/acl9/compare/trailblazer) for adding an acl9-like DSL to trailblazer `Operation`s.  I think it was working nicely.

It really should/needs to be a separate gem like `trailblazer-acl9` that you can add and which has `acl9` as a dependency.  Might still need the conditional stuff for adding to Rails (or might need to make that a separate gem too).  I will only get around to doing this if I start using trailblazer again (which is unlikely).

In any case if you want to play around, see if it works.  As you can see in the diff it creates a `policy` method instead of an `access_control` method, and you'll need to explicitly `include Acl9` in your `Operation` (or do it for the base class somewhere), it's fairly self contained and the interface didn't change from 2 to 3, so it probably just works™ :)

Feel free to reopen this issue with more details if I misunderstood.

**Comment by night91** [comment]
I am trying to find out how to make the same but with trailblazer 2.0, so ading the support for acl9 to trailblazer 2.0, but I have never wrote a DSL alike before, any hits or a please to read about it?

**Comment by smathy** [comment]
Well, basically all [the trailblazer code](https://github.com/be9/acl9/compare/trailblazer) does is define a `setup!` method that raises an exception if the supplied `policy` block doesn't evaluate to true.  The Trb2.0 APIs have changed dramatically and I'm not that familiar with it, but a quick look suggests you might be able to just do `step :setup!` in your operation, or perhaps you need to define a step in your operations like: `step Policy::Guard( :setup! )`.  And maybe you need to also redefine the `setup!` defined in [the trailblazer code](https://github.com/be9/acl9/compare/trailblazer) for the new method signature (arguments being passed to the `step` methods.

**Comment by smathy** [comment]
If that's too hard for you then maybe it'd be easier for you to just switch over to using Pundit.  You can still use (if you choose) the [Role Subsystem](https://github.com/be9/acl9/wiki/Role-Subsystem) from acl9, but use Pundit policies to define the authorization part instead of the `policy` block.

**Comment by night91** [comment]
Do you remember Eos Project? Well I am upgrading some stuff :)

**Comment by night91** [comment]
Cause the policy is not seen by the operation in the version 2.

**Comment by smathy** [comment]
Yes, I had assumed you were upgrading that app.  That doesn't change the advice I've already given.

**Comment by night91** [comment]
Thank you, i will check the way with Pundit for auth and Acl9 for the roles.
