### ISSUE TITLE
Error when calling user.has_role! :admin, nil

### ISSUE THREAD

**Issue by night91** [be9/acl9#109]
I see in the last commit there was a check for to prevent passing the object as nil.

Now:
`user.has_role! :admin`  this is valid
`user.has_role! :admin, nil`  this is invalid

This caused some things broken in my project. What was the idea of this check?

**Comment by smathy** [comment]
Sorry, I thought afterwards that I should have bumped to `4` version because strictly speaking it was backwardly incompatible.

The idea is to prevent unintentionally creating a global user (when `protect_global_roles` is true), previously this would have created a global `:admin`:

```ruby
  department = Department.find_by name: misspelled_name
  user.has_role! :admin, department   # same effect as `user.has_role! :admin`
```

And when `protect_global_roles` was false, this would have been an privilege bleed:

```ruby
  user.has_role! :admin, actual_department
  department = Department.find_by name: misspelled_name
  user.has_role? :admin, department   # same effect as `user.has_role? :admin`
```
