### ISSUE TITLE
List a user's roles

### ISSUE THREAD

**Issue by brancusi** [be9/acl9#92]
Hi,

Is there a way to list all subject roles a user has?

If a user has ```:admin``` and ```:dancer``` roles as an example.

I see a method for ```user.roles_for(Object)```, but something like, ```user.roles``` would be useful for us if not already available.

Thank you

**Comment by kawikak** [comment]
A simple accessor for this would be nice. For now you can do

`user.role_objects.map(&:name)`

This will return all roles regardless of object context (or lack thereof)

**Comment by smathy** [comment]
I'll tell you why I keep resisting this request.  It's so easy to do this yourself, there's generally only one subject model, so you'd only be adding one method to one model, and for the simple use case that most people seem to be interested in, the method is literally this:

```ruby
def role_names
  role_objects.pluck :name
end
```

...so it's super-simple, and we don't gain much by adding it as part of this gem.

**PLUS** the more methods we add, especially instance methods, the more likely we are to clash with a user's existing methods in their own models. So generally, there's a high burden for new instance methods, and because this is so simple to implement yourself I don't feel that that burden has been reached.

There's also one other thing, although I understand that a lot of users use acl9 for very simple roles, there are many users who use the object features of acl9, so they don't just have roles like `:admin` and `:dancer` but they have roles like: `:admin, on: School` or `:admin, on: School.find(42)`, and so the representation of all the roles that a given user has becomes problematic, if `protect_global_roles` is `true` then a global `:admin` and the `:admin` of a particular school are both going to have `:admin` in their `:role_names`, so really you need to show both the role name and the list of objects that role applies to - and by then really even with a `role_names` method many acl9 users will end up having to code their own logic anyway.

So, for all these reasons, I'm not adding this feature, sorry.
